import type { ToolCategory, ToolDefinition } from "./types";

export const CATEGORY_META: Record<ToolCategory, { label: string; description: string }> = {
  image: { label: "Imagem", description: "Otimização, transparência, privacidade e análise visual." },
  video: { label: "Vídeo", description: "Conversão, compressão, cortes, áudio e quadros no navegador." },
  security: { label: "Segurança de arquivos", description: "Criptografia, integridade e análise de senhas sem enviar arquivos." },
  assets: { label: "Recursos visuais", description: "Cores, contraste, paletas e pacotes de ícones prontos para uso." },
};

export const TOOLS: ToolDefinition[] = [
  {
    id: "image-optimize",
    name: "Otimizar imagem",
    shortName: "Otimizar",
    description: "Compacte, converta e redimensione JPEG, PNG, WebP e AVIF com métricas de resultado.",
    category: "image",
    icon: "ImageDown",
    help: {
      summary: "Reduz peso, troca formato e/ou limita a dimensão máxima de uma imagem.",
      input: "JPEG, PNG, WebP ou AVIF. Para perceber bem a diferença, use uma foto grande.",
      steps: ["Envie a imagem.", "Escolha formato, dimensão máxima e qualidade.", "Processe e compare tamanho, resolução e pré-visualização."],
      expected: "Uma nova imagem válida no formato escolhido, com as métricas do antes e depois.",
    },
  },
  {
    id: "background-remove",
    name: "Remover fundo",
    shortName: "Fundo transparente",
    description: "Crie PNG com canal alpha usando detecção de fundo por bordas, tolerância e suavização.",
    category: "image",
    icon: "ScanLine",
    localOnly: true,
    help: {
      summary: "Remove fundos relativamente uniformes conectados às bordas e gera transparência.",
      input: "PNG/JPEG/WebP com objeto bem separado de um fundo branco, cinza ou de cor uniforme.",
      steps: ["Envie a imagem.", "Ajuste tolerância e suavização se necessário.", "Baixe o PNG transparente."],
      expected: "O fundo some e o objeto principal permanece, com bordas suavizadas.",
      note: "Não é segmentação por IA; cenários complexos podem exigir outra ferramenta.",
    },
  },
  {
    id: "metadata-cleaner",
    name: "Privacidade e metadados",
    shortName: "Privacidade",
    description: "Inspecione EXIF, identifique GPS e gere uma cópia limpa sem metadados embutidos.",
    category: "image",
    icon: "ShieldCheck",
    localOnly: true,
    help: {
      summary: "Mostra dados embutidos na foto — inclusive GPS quando houver — e cria uma cópia sem esses blocos de metadados.",
      input: "Foto original de celular/câmera. JPEG é ótimo para teste; HEIC/HEIF de iPhone também é aceito e convertido localmente para limpeza.",
      steps: ["Envie a foto original.", "Confira EXIF/GPS encontrados.", "Clique em Remover metadados e baixe a cópia limpa.", "Reenvie a cópia limpa para confirmar."],
      expected: "A nova imagem mantém o conteúdo visual, mas os metadados sensíveis deixam de aparecer.",
    },
  },
  {
    id: "image-compare",
    name: "Comparar imagens",
    shortName: "Comparar imagens",
    description: "Compare duas versões com divisor interativo, percentual de diferença e mapa visual de alterações.",
    category: "image",
    icon: "Columns2",
    localOnly: true,
    help: {
      summary: "Compara duas imagens e destaca exatamente onde elas mudaram.",
      input: "Duas versões da mesma tela/arte. Para logos em tamanhos ou margens diferentes, use o modo Conteúdo normalizado.",
      steps: ["Envie a versão A e a versão B.", "Escolha Layout exato ou Conteúdo normalizado.", "Ajuste o limiar apenas se mudanças muito sutis estiverem sendo ignoradas.", "Analise o divisor interativo e o mapa de diferenças."],
      expected: "Imagens iguais ficam próximas de 0% de alteração; mudanças localizadas aparecem em laranja/vermelho no mapa.",
      note: "Duas imagens realmente diferentes podem chegar a 100%; isso não significa erro por si só.",
    },
  },
  {
    id: "palette-extract",
    name: "Extrair paleta",
    shortName: "Paleta",
    description: "Extraia cores dominantes de uma imagem e copie HEX e variáveis CSS.",
    category: "image",
    icon: "Palette",
    localOnly: true,
    help: {
      summary: "Encontra as cores que mais aparecem em uma imagem.",
      input: "Qualquer imagem legível pelo navegador.",
      steps: ["Envie a imagem.", "Confira as cores dominantes.", "Copie os HEX ou baixe as variáveis CSS."],
      expected: "Até oito cores dominantes coerentes com a imagem enviada.",
    },
  },
  {
    id: "asset-pack",
    name: "Pacote de assets",
    shortName: "Pacote de assets",
    description: "Gere favicons, ícones PWA, Apple Touch e tamanhos Android em um ZIP organizado.",
    category: "assets",
    icon: "PackageOpen",
    localOnly: true,
    help: {
      summary: "Transforma um logo/ícone em vários tamanhos usados por sites e aplicativos.",
      input: "PNG, JPEG ou WebP, preferencialmente quadrado e com boa resolução.",
      steps: ["Envie o ícone.", "Confira as pré-visualizações.", "Gere e baixe o ZIP."],
      expected: "ZIP com favicons, Apple Touch, PWA, Android e site.webmanifest.",
    },
  },
  {
    id: "video-lab",
    name: "Processar vídeo",
    shortName: "Vídeo",
    description: "Comprima, converta, corte, extraia áudio ou gere um quadro com processamento local no navegador.",
    category: "video",
    icon: "Clapperboard",
    localOnly: true,
    help: {
      summary: "Executa operações comuns de vídeo sem enviar o arquivo para o servidor.",
      input: "MP4, WebM e outros contêineres comuns. Capturas de tela do Ubuntu em WebM são suportadas.",
      steps: ["Envie o vídeo.", "Escolha a operação.", "Ajuste as opções quando aparecerem.", "Execute e baixe o resultado."],
      expected: "O resultado deve abrir normalmente e corresponder à operação escolhida.",
      note: "O mecanismo de vídeo é carregado na primeira execução. A extração de quadro também tenta usar o próprio navegador quando possível.",
    },
  },
  {
    id: "file-crypto",
    name: "Criptografar arquivo",
    shortName: "Criptografia",
    description: "Proteja e recupere arquivos com PBKDF2 + AES-GCM autenticado diretamente no navegador.",
    category: "security",
    icon: "LockKeyhole",
    localOnly: true,
    help: {
      summary: "Protege qualquer arquivo com senha e depois permite recuperar exatamente o original.",
      input: "Qualquer arquivo. Um TXT pequeno é o teste mais fácil de conferir.",
      steps: ["Criptografe o arquivo com uma senha de pelo menos 8 caracteres.", "Baixe o .mediaforge.", "Troque para Descriptografar, envie o .mediaforge e use a mesma senha.", "Abra o arquivo recuperado."],
      expected: "A senha correta recupera o nome e conteúdo originais; uma senha errada deve falhar.",
    },
  },
  {
    id: "checksum",
    name: "Hash e integridade",
    shortName: "Hash",
    description: "Calcule SHA-256/SHA-512 e valide arquivos contra hashes esperados.",
    category: "security",
    icon: "Fingerprint",
    localOnly: true,
    help: {
      summary: "Cria uma impressão digital do arquivo para provar se ele continua byte a byte igual.",
      input: "Qualquer arquivo. Para teste, use dois TXT quase iguais mudando apenas um caractere.",
      steps: ["Calcule o hash do primeiro arquivo.", "Cole esse valor em Hash esperado.", "O mesmo arquivo deve validar.", "Envie uma versão alterada e calcule novamente."],
      expected: "Arquivo original = hash correspondente; arquivo alterado = hash diferente.",
    },
  },
  {
    id: "password-lab",
    name: "Gerador e análise de senhas",
    shortName: "Senhas",
    description: "Gere senhas, estime entropia e visualize cenários teóricos de resistência a tentativas.",
    category: "security",
    icon: "KeyRound",
    localOnly: true,
    help: {
      summary: "Gera senhas aleatórias e estima força com base em comprimento e variedade de caracteres.",
      input: "Não usa arquivo. Digite uma senha ou gere uma nova.",
      steps: ["Teste uma senha curta.", "Compare requisitos e entropia.", "Gere uma senha longa e compare novamente."],
      expected: "Senhas maiores e variadas recebem estimativas superiores.",
    },
  },
  {
    id: "color-studio",
    name: "Cores e contraste",
    shortName: "Cores",
    description: "Converta HEX/RGB/HSL, gere harmonias e valide contraste WCAG em tempo real.",
    category: "assets",
    icon: "Blend",
    localOnly: true,
    help: {
      summary: "Converte uma cor, cria combinações e mede legibilidade entre texto e fundo.",
      input: "Valores de cor; não precisa enviar arquivo.",
      steps: ["Escolha uma cor base.", "Confira HEX/RGB/HSL e harmonias.", "Defina texto e fundo para validar contraste."],
      expected: "Preto sobre branco deve chegar perto de 21:1; cores iguais ficam em 1:1.",
    },
  },
  {
    id: "gradient-builder",
    name: "Criador de gradientes",
    shortName: "Gradientes",
    description: "Monte gradientes CSS com direção, três cores, pré-visualização e código pronto para copiar.",
    category: "assets",
    icon: "WandSparkles",
    localOnly: true,
    help: {
      summary: "Cria um degradê visual e entrega o CSS correspondente.",
      input: "Três cores e um ângulo; não precisa enviar arquivo.",
      steps: ["Escolha as três cores.", "Ajuste o ângulo.", "Copie ou baixe o CSS."],
      expected: "A pré-visualização deve acompanhar os controles e o CSS deve reproduzir o mesmo degradê.",
    },
  },
];

export function getTool(id: string | undefined): ToolDefinition {
  return TOOLS.find((tool) => tool.id === id) ?? TOOLS[0];
}
